[package]
name = "vata"
version = "0.1.0"
edition = "2024"

[features]
telemetry = []

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
tikv-jemallocator = "0.6"
tokio = { version = "1.52.3", default-features = false, features = [
    "rt",
    "process",
    "fs",
    "rt-multi-thread",
    "macros",
    "net",
    "sync",
    "time",
] }
toml = "1.1.6"
[[bench]]
name = "arena_bench"
harness = false

[[bench]]
name = "arena_workload"
harness = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[profile.release]
opt-level = 3
lto = "fat" 
codegen-units = 1
panic = "abort"
